#ifndef M101_HARDWARE_CONFIG_H
#define M101_HARDWARE_CONFIG_H

#define PIN_START_BUTTON 0
#define PIN_LEFT_BACK_LINE_SENSOR 2
#define PIN_RIGHT_BACK_LINE_SENSOR 3
#define PIN_LEFT_FRONT_LINE_SENSOR 4
#define PIN_RIGHT_FRONT_LINE_SENSOR 5
#define PIN_MAGNETIC_SENSOR 6
#define PIN_CONTAMINATION_LED 7
#define PIN_NO_CONTAMINATION_LED 8
#define PIN_DRIVING_STATUS_LED 9
#define PIN_TOUCH_SENSOR 10
#define PIN_SERVO_CLAW 11
#define PIN_SERVO_LIFT 12

#define SAMPLE_RATE_IMU_HZ 10

#define MOTOR_LEFT 1
#define MOTOR_RIGHT 2

#endif // M101_HARDWARE_CONFIG_H
